services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: php_apache_ruloff
    volumes:
      - ./apache/ruloff:/var/www/html
      - ./apache/logs:/var/log/apache2
      - ./certbot/www:/var/www/html/public/.well-known
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - apache_network
    env_file:
      - ./apache/ruloff/.env 
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: certbot_ruloff
    volumes:
      - ./certbot/www:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/html --quiet; done"
    networks:
      - apache_network
    restart: always

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: mysql_ruloff
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - apache_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  apache_network:
    driver: bridge

volumes:
  mysql_data:
    external: true
