services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: php_apache_ruloff
    volumes:
      - ./apache/ruloff:/var/www/html
      - ./apache/logs:/var/log/apache2
    ports:
      - "80:80"
    networks:
      - apache_network
    environment:
      - ENVIRONMENT=production
    env_file:
      - ./apache/ruloff/.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_ruloff
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - apache_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  apache_network:
    driver: bridge

volumes:
  mysql_data:
    external: true
