services:
  apache:
    build: .
    container_name: php_apache_1
    volumes:
      - ./apache:/var/www/html
    ports:
      - "8080:80"
    networks:
      - apache_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: QaEP4CnuLfrqWMvA8UjSdD
      MYSQL_DATABASE: database
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - apache_network

networks:
  apache_network:
    driver: bridge

volumes:
  mysql_data: